// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: poker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to evaluate a single hand
type EvaluateHandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HoleCards      []string               `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`                // 2 cards (e.g., ["HA", "S7"])
	CommunityCards []string               `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"` // 5 cards (e.g., ["CT", "DK", "H5", "S2", "C9"])
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateHandRequest) Reset() {
	*x = EvaluateHandRequest{}
	mi := &file_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandRequest) ProtoMessage() {}

func (x *EvaluateHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandRequest.ProtoReflect.Descriptor instead.
func (*EvaluateHandRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateHandRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *EvaluateHandRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

// Response with hand evaluation
type EvaluateHandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestHand      string                 `protobuf:"bytes,1,opt,name=best_hand,json=bestHand,proto3" json:"best_hand,omitempty"`                  // Hand type (e.g., "Three of a Kind", "Flush", "Royal Flush")
	HandValue     int32                  `protobuf:"varint,2,opt,name=hand_value,json=handValue,proto3" json:"hand_value,omitempty"`              // Numeric value for comparison (higher is better)
	BestFiveCards []string               `protobuf:"bytes,3,rep,name=best_five_cards,json=bestFiveCards,proto3" json:"best_five_cards,omitempty"` // The 5 cards that make the best hand
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandResponse) Reset() {
	*x = EvaluateHandResponse{}
	mi := &file_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandResponse) ProtoMessage() {}

func (x *EvaluateHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandResponse.ProtoReflect.Descriptor instead.
func (*EvaluateHandResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateHandResponse) GetBestHand() string {
	if x != nil {
		return x.BestHand
	}
	return ""
}

func (x *EvaluateHandResponse) GetHandValue() int32 {
	if x != nil {
		return x.HandValue
	}
	return 0
}

func (x *EvaluateHandResponse) GetBestFiveCards() []string {
	if x != nil {
		return x.BestFiveCards
	}
	return nil
}

// Request to compare two hands
type CompareHandsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Player1HoleCards      []string               `protobuf:"bytes,1,rep,name=player1_hole_cards,json=player1HoleCards,proto3" json:"player1_hole_cards,omitempty"`                // Player 1's 2 hole cards
	Player1CommunityCards []string               `protobuf:"bytes,2,rep,name=player1_community_cards,json=player1CommunityCards,proto3" json:"player1_community_cards,omitempty"` // 5 community cards
	Player2HoleCards      []string               `protobuf:"bytes,3,rep,name=player2_hole_cards,json=player2HoleCards,proto3" json:"player2_hole_cards,omitempty"`                // Player 2's 2 hole cards
	Player2CommunityCards []string               `protobuf:"bytes,4,rep,name=player2_community_cards,json=player2CommunityCards,proto3" json:"player2_community_cards,omitempty"` // 5 community cards
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CompareHandsRequest) Reset() {
	*x = CompareHandsRequest{}
	mi := &file_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsRequest) ProtoMessage() {}

func (x *CompareHandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsRequest.ProtoReflect.Descriptor instead.
func (*CompareHandsRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{2}
}

func (x *CompareHandsRequest) GetPlayer1HoleCards() []string {
	if x != nil {
		return x.Player1HoleCards
	}
	return nil
}

func (x *CompareHandsRequest) GetPlayer1CommunityCards() []string {
	if x != nil {
		return x.Player1CommunityCards
	}
	return nil
}

func (x *CompareHandsRequest) GetPlayer2HoleCards() []string {
	if x != nil {
		return x.Player2HoleCards
	}
	return nil
}

func (x *CompareHandsRequest) GetPlayer2CommunityCards() []string {
	if x != nil {
		return x.Player2CommunityCards
	}
	return nil
}

// Response with comparison results
type CompareHandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1Hand   *EvaluateHandResponse  `protobuf:"bytes,1,opt,name=player1_hand,json=player1Hand,proto3" json:"player1_hand,omitempty"`
	Player2Hand   *EvaluateHandResponse  `protobuf:"bytes,2,opt,name=player2_hand,json=player2Hand,proto3" json:"player2_hand,omitempty"`
	Winner        int32                  `protobuf:"varint,3,opt,name=winner,proto3" json:"winner,omitempty"` // 1 for player1, 2 for player2, 0 for tie
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareHandsResponse) Reset() {
	*x = CompareHandsResponse{}
	mi := &file_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsResponse) ProtoMessage() {}

func (x *CompareHandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsResponse.ProtoReflect.Descriptor instead.
func (*CompareHandsResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{3}
}

func (x *CompareHandsResponse) GetPlayer1Hand() *EvaluateHandResponse {
	if x != nil {
		return x.Player1Hand
	}
	return nil
}

func (x *CompareHandsResponse) GetPlayer2Hand() *EvaluateHandResponse {
	if x != nil {
		return x.Player2Hand
	}
	return nil
}

func (x *CompareHandsResponse) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

// Request for probability calculation
type ProbabilityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HoleCards      []string               `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`                 // 2 hole cards
	CommunityCards []string               `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`  // 0, 3, 4, or 5 community cards
	NumPlayers     int32                  `protobuf:"varint,3,opt,name=num_players,json=numPlayers,proto3" json:"num_players,omitempty"`             // Number of players (including the one with hole_cards)
	NumSimulations int32                  `protobuf:"varint,4,opt,name=num_simulations,json=numSimulations,proto3" json:"num_simulations,omitempty"` // Number of Monte Carlo simulations
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbabilityRequest) Reset() {
	*x = ProbabilityRequest{}
	mi := &file_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbabilityRequest) ProtoMessage() {}

func (x *ProbabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbabilityRequest.ProtoReflect.Descriptor instead.
func (*ProbabilityRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{4}
}

func (x *ProbabilityRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *ProbabilityRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *ProbabilityRequest) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

func (x *ProbabilityRequest) GetNumSimulations() int32 {
	if x != nil {
		return x.NumSimulations
	}
	return 0
}

// Response with probability
type ProbabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WinProbability float64                `protobuf:"fixed64,1,opt,name=win_probability,json=winProbability,proto3" json:"win_probability,omitempty"` // Probability of winning (0.0 to 1.0)
	TieProbability float64                `protobuf:"fixed64,2,opt,name=tie_probability,json=tieProbability,proto3" json:"tie_probability,omitempty"` // Probability of tying (0.0 to 1.0)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbabilityResponse) Reset() {
	*x = ProbabilityResponse{}
	mi := &file_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbabilityResponse) ProtoMessage() {}

func (x *ProbabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbabilityResponse.ProtoReflect.Descriptor instead.
func (*ProbabilityResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{5}
}

func (x *ProbabilityResponse) GetWinProbability() float64 {
	if x != nil {
		return x.WinProbability
	}
	return 0
}

func (x *ProbabilityResponse) GetTieProbability() float64 {
	if x != nil {
		return x.TieProbability
	}
	return 0
}

var File_poker_proto protoreflect.FileDescriptor

const file_poker_proto_rawDesc = "" +
	"\n" +
	"\vpoker.proto\x12\x05poker\"]\n" +
	"\x13EvaluateHandRequest\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x01 \x03(\tR\tholeCards\x12'\n" +
	"\x0fcommunity_cards\x18\x02 \x03(\tR\x0ecommunityCards\"z\n" +
	"\x14EvaluateHandResponse\x12\x1b\n" +
	"\tbest_hand\x18\x01 \x01(\tR\bbestHand\x12\x1d\n" +
	"\n" +
	"hand_value\x18\x02 \x01(\x05R\thandValue\x12&\n" +
	"\x0fbest_five_cards\x18\x03 \x03(\tR\rbestFiveCards\"\xe1\x01\n" +
	"\x13CompareHandsRequest\x12,\n" +
	"\x12player1_hole_cards\x18\x01 \x03(\tR\x10player1HoleCards\x126\n" +
	"\x17player1_community_cards\x18\x02 \x03(\tR\x15player1CommunityCards\x12,\n" +
	"\x12player2_hole_cards\x18\x03 \x03(\tR\x10player2HoleCards\x126\n" +
	"\x17player2_community_cards\x18\x04 \x03(\tR\x15player2CommunityCards\"\xae\x01\n" +
	"\x14CompareHandsResponse\x12>\n" +
	"\fplayer1_hand\x18\x01 \x01(\v2\x1b.poker.EvaluateHandResponseR\vplayer1Hand\x12>\n" +
	"\fplayer2_hand\x18\x02 \x01(\v2\x1b.poker.EvaluateHandResponseR\vplayer2Hand\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\x05R\x06winner\"\xa6\x01\n" +
	"\x12ProbabilityRequest\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x01 \x03(\tR\tholeCards\x12'\n" +
	"\x0fcommunity_cards\x18\x02 \x03(\tR\x0ecommunityCards\x12\x1f\n" +
	"\vnum_players\x18\x03 \x01(\x05R\n" +
	"numPlayers\x12'\n" +
	"\x0fnum_simulations\x18\x04 \x01(\x05R\x0enumSimulations\"g\n" +
	"\x13ProbabilityResponse\x12'\n" +
	"\x0fwin_probability\x18\x01 \x01(\x01R\x0ewinProbability\x12'\n" +
	"\x0ftie_probability\x18\x02 \x01(\x01R\x0etieProbability2\xf4\x01\n" +
	"\x0ePokerEvaluator\x12G\n" +
	"\fEvaluateHand\x12\x1a.poker.EvaluateHandRequest\x1a\x1b.poker.EvaluateHandResponse\x12G\n" +
	"\fCompareHands\x12\x1a.poker.CompareHandsRequest\x1a\x1b.poker.CompareHandsResponse\x12P\n" +
	"\x17CalculateWinProbability\x12\x19.poker.ProbabilityRequest\x1a\x1a.poker.ProbabilityResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_poker_proto_rawDescOnce sync.Once
	file_poker_proto_rawDescData []byte
)

func file_poker_proto_rawDescGZIP() []byte {
	file_poker_proto_rawDescOnce.Do(func() {
		file_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)))
	})
	return file_poker_proto_rawDescData
}

var file_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_poker_proto_goTypes = []any{
	(*EvaluateHandRequest)(nil),  // 0: poker.EvaluateHandRequest
	(*EvaluateHandResponse)(nil), // 1: poker.EvaluateHandResponse
	(*CompareHandsRequest)(nil),  // 2: poker.CompareHandsRequest
	(*CompareHandsResponse)(nil), // 3: poker.CompareHandsResponse
	(*ProbabilityRequest)(nil),   // 4: poker.ProbabilityRequest
	(*ProbabilityResponse)(nil),  // 5: poker.ProbabilityResponse
}
var file_poker_proto_depIdxs = []int32{
	1, // 0: poker.CompareHandsResponse.player1_hand:type_name -> poker.EvaluateHandResponse
	1, // 1: poker.CompareHandsResponse.player2_hand:type_name -> poker.EvaluateHandResponse
	0, // 2: poker.PokerEvaluator.EvaluateHand:input_type -> poker.EvaluateHandRequest
	2, // 3: poker.PokerEvaluator.CompareHands:input_type -> poker.CompareHandsRequest
	4, // 4: poker.PokerEvaluator.CalculateWinProbability:input_type -> poker.ProbabilityRequest
	1, // 5: poker.PokerEvaluator.EvaluateHand:output_type -> poker.EvaluateHandResponse
	3, // 6: poker.PokerEvaluator.CompareHands:output_type -> poker.CompareHandsResponse
	5, // 7: poker.PokerEvaluator.CalculateWinProbability:output_type -> poker.ProbabilityResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poker_proto_init() }
func file_poker_proto_init() {
	if File_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poker_proto_goTypes,
		DependencyIndexes: file_poker_proto_depIdxs,
		MessageInfos:      file_poker_proto_msgTypes,
	}.Build()
	File_poker_proto = out.File
	file_poker_proto_goTypes = nil
	file_poker_proto_depIdxs = nil
}
