// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: poker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokerEvaluator_EvaluateHand_FullMethodName            = "/poker.PokerEvaluator/EvaluateHand"
	PokerEvaluator_CompareHands_FullMethodName            = "/poker.PokerEvaluator/CompareHands"
	PokerEvaluator_CalculateWinProbability_FullMethodName = "/poker.PokerEvaluator/CalculateWinProbability"
)

// PokerEvaluatorClient is the client API for PokerEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PokerEvaluator service for Texas Hold'em poker hand evaluation and probability calculation
type PokerEvaluatorClient interface {
	// EvaluateHand evaluates the best hand from 2 hole cards + 5 community cards
	EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error)
	// CompareHands compares two hands (each with 2 hole cards + 5 community cards) and determines the winner
	CompareHands(ctx context.Context, in *CompareHandsRequest, opts ...grpc.CallOption) (*CompareHandsResponse, error)
	// CalculateWinProbability calculates the probability of winning using Monte Carlo simulation
	CalculateWinProbability(ctx context.Context, in *ProbabilityRequest, opts ...grpc.CallOption) (*ProbabilityResponse, error)
}

type pokerEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewPokerEvaluatorClient(cc grpc.ClientConnInterface) PokerEvaluatorClient {
	return &pokerEvaluatorClient{cc}
}

func (c *pokerEvaluatorClient) EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateHandResponse)
	err := c.cc.Invoke(ctx, PokerEvaluator_EvaluateHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerEvaluatorClient) CompareHands(ctx context.Context, in *CompareHandsRequest, opts ...grpc.CallOption) (*CompareHandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareHandsResponse)
	err := c.cc.Invoke(ctx, PokerEvaluator_CompareHands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerEvaluatorClient) CalculateWinProbability(ctx context.Context, in *ProbabilityRequest, opts ...grpc.CallOption) (*ProbabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbabilityResponse)
	err := c.cc.Invoke(ctx, PokerEvaluator_CalculateWinProbability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerEvaluatorServer is the server API for PokerEvaluator service.
// All implementations must embed UnimplementedPokerEvaluatorServer
// for forward compatibility.
//
// PokerEvaluator service for Texas Hold'em poker hand evaluation and probability calculation
type PokerEvaluatorServer interface {
	// EvaluateHand evaluates the best hand from 2 hole cards + 5 community cards
	EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error)
	// CompareHands compares two hands (each with 2 hole cards + 5 community cards) and determines the winner
	CompareHands(context.Context, *CompareHandsRequest) (*CompareHandsResponse, error)
	// CalculateWinProbability calculates the probability of winning using Monte Carlo simulation
	CalculateWinProbability(context.Context, *ProbabilityRequest) (*ProbabilityResponse, error)
	mustEmbedUnimplementedPokerEvaluatorServer()
}

// UnimplementedPokerEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokerEvaluatorServer struct{}

func (UnimplementedPokerEvaluatorServer) EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateHand not implemented")
}
func (UnimplementedPokerEvaluatorServer) CompareHands(context.Context, *CompareHandsRequest) (*CompareHandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareHands not implemented")
}
func (UnimplementedPokerEvaluatorServer) CalculateWinProbability(context.Context, *ProbabilityRequest) (*ProbabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateWinProbability not implemented")
}
func (UnimplementedPokerEvaluatorServer) mustEmbedUnimplementedPokerEvaluatorServer() {}
func (UnimplementedPokerEvaluatorServer) testEmbeddedByValue()                        {}

// UnsafePokerEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokerEvaluatorServer will
// result in compilation errors.
type UnsafePokerEvaluatorServer interface {
	mustEmbedUnimplementedPokerEvaluatorServer()
}

func RegisterPokerEvaluatorServer(s grpc.ServiceRegistrar, srv PokerEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedPokerEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokerEvaluator_ServiceDesc, srv)
}

func _PokerEvaluator_EvaluateHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerEvaluatorServer).EvaluateHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerEvaluator_EvaluateHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerEvaluatorServer).EvaluateHand(ctx, req.(*EvaluateHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerEvaluator_CompareHands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareHandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerEvaluatorServer).CompareHands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerEvaluator_CompareHands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerEvaluatorServer).CompareHands(ctx, req.(*CompareHandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerEvaluator_CalculateWinProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerEvaluatorServer).CalculateWinProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerEvaluator_CalculateWinProbability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerEvaluatorServer).CalculateWinProbability(ctx, req.(*ProbabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokerEvaluator_ServiceDesc is the grpc.ServiceDesc for PokerEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokerEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poker.PokerEvaluator",
	HandlerType: (*PokerEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateHand",
			Handler:    _PokerEvaluator_EvaluateHand_Handler,
		},
		{
			MethodName: "CompareHands",
			Handler:    _PokerEvaluator_CompareHands_Handler,
		},
		{
			MethodName: "CalculateWinProbability",
			Handler:    _PokerEvaluator_CalculateWinProbability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poker.proto",
}
