// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: temperature.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperatureConverter_ConvertCelsiusToFahrenheit_FullMethodName = "/temperature.TemperatureConverter/ConvertCelsiusToFahrenheit"
	TemperatureConverter_ConvertFahrenheitToCelsius_FullMethodName = "/temperature.TemperatureConverter/ConvertFahrenheitToCelsius"
)

// TemperatureConverterClient is the client API for TemperatureConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TemperatureConverter service for converting between Celsius and Fahrenheit
type TemperatureConverterClient interface {
	// ConvertCelsiusToFahrenheit converts Celsius to Fahrenheit
	ConvertCelsiusToFahrenheit(ctx context.Context, in *CelsiusRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
	// ConvertFahrenheitToCelsius converts Fahrenheit to Celsius
	ConvertFahrenheitToCelsius(ctx context.Context, in *FahrenheitRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
}

type temperatureConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureConverterClient(cc grpc.ClientConnInterface) TemperatureConverterClient {
	return &temperatureConverterClient{cc}
}

func (c *temperatureConverterClient) ConvertCelsiusToFahrenheit(ctx context.Context, in *CelsiusRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureConverter_ConvertCelsiusToFahrenheit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureConverterClient) ConvertFahrenheitToCelsius(ctx context.Context, in *FahrenheitRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureConverter_ConvertFahrenheitToCelsius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperatureConverterServer is the server API for TemperatureConverter service.
// All implementations must embed UnimplementedTemperatureConverterServer
// for forward compatibility.
//
// TemperatureConverter service for converting between Celsius and Fahrenheit
type TemperatureConverterServer interface {
	// ConvertCelsiusToFahrenheit converts Celsius to Fahrenheit
	ConvertCelsiusToFahrenheit(context.Context, *CelsiusRequest) (*TemperatureResponse, error)
	// ConvertFahrenheitToCelsius converts Fahrenheit to Celsius
	ConvertFahrenheitToCelsius(context.Context, *FahrenheitRequest) (*TemperatureResponse, error)
	mustEmbedUnimplementedTemperatureConverterServer()
}

// UnimplementedTemperatureConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperatureConverterServer struct{}

func (UnimplementedTemperatureConverterServer) ConvertCelsiusToFahrenheit(context.Context, *CelsiusRequest) (*TemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertCelsiusToFahrenheit not implemented")
}
func (UnimplementedTemperatureConverterServer) ConvertFahrenheitToCelsius(context.Context, *FahrenheitRequest) (*TemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertFahrenheitToCelsius not implemented")
}
func (UnimplementedTemperatureConverterServer) mustEmbedUnimplementedTemperatureConverterServer() {}
func (UnimplementedTemperatureConverterServer) testEmbeddedByValue()                              {}

// UnsafeTemperatureConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureConverterServer will
// result in compilation errors.
type UnsafeTemperatureConverterServer interface {
	mustEmbedUnimplementedTemperatureConverterServer()
}

func RegisterTemperatureConverterServer(s grpc.ServiceRegistrar, srv TemperatureConverterServer) {
	// If the following call panics, it indicates UnimplementedTemperatureConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperatureConverter_ServiceDesc, srv)
}

func _TemperatureConverter_ConvertCelsiusToFahrenheit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CelsiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertCelsiusToFahrenheit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureConverter_ConvertCelsiusToFahrenheit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertCelsiusToFahrenheit(ctx, req.(*CelsiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureConverter_ConvertFahrenheitToCelsius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FahrenheitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertFahrenheitToCelsius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureConverter_ConvertFahrenheitToCelsius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertFahrenheitToCelsius(ctx, req.(*FahrenheitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperatureConverter_ServiceDesc is the grpc.ServiceDesc for TemperatureConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperature.TemperatureConverter",
	HandlerType: (*TemperatureConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertCelsiusToFahrenheit",
			Handler:    _TemperatureConverter_ConvertCelsiusToFahrenheit_Handler,
		},
		{
			MethodName: "ConvertFahrenheitToCelsius",
			Handler:    _TemperatureConverter_ConvertFahrenheitToCelsius_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temperature.proto",
}
