// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: temperature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request with Celsius temperature
type CelsiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusRequest) Reset() {
	*x = CelsiusRequest{}
	mi := &file_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusRequest) ProtoMessage() {}

func (x *CelsiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusRequest.ProtoReflect.Descriptor instead.
func (*CelsiusRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *CelsiusRequest) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

// Request with Fahrenheit temperature
type FahrenheitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fahrenheit    float64                `protobuf:"fixed64,1,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitRequest) Reset() {
	*x = FahrenheitRequest{}
	mi := &file_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitRequest) ProtoMessage() {}

func (x *FahrenheitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitRequest.ProtoReflect.Descriptor instead.
func (*FahrenheitRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *FahrenheitRequest) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

// Response with both Celsius and Fahrenheit temperatures
type TemperatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	Fahrenheit    float64                `protobuf:"fixed64,2,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureResponse) Reset() {
	*x = TemperatureResponse{}
	mi := &file_temperature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureResponse) ProtoMessage() {}

func (x *TemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureResponse.ProtoReflect.Descriptor instead.
func (*TemperatureResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{2}
}

func (x *TemperatureResponse) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

func (x *TemperatureResponse) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

var File_temperature_proto protoreflect.FileDescriptor

const file_temperature_proto_rawDesc = "" +
	"\n" +
	"\x11temperature.proto\x12\vtemperature\"*\n" +
	"\x0eCelsiusRequest\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius\"3\n" +
	"\x11FahrenheitRequest\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x01 \x01(\x01R\n" +
	"fahrenheit\"O\n" +
	"\x13TemperatureResponse\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x02 \x01(\x01R\n" +
	"fahrenheit2\xd3\x01\n" +
	"\x14TemperatureConverter\x12[\n" +
	"\x1aConvertCelsiusToFahrenheit\x12\x1b.temperature.CelsiusRequest\x1a .temperature.TemperatureResponse\x12^\n" +
	"\x1aConvertFahrenheitToCelsius\x12\x1e.temperature.FahrenheitRequest\x1a .temperature.TemperatureResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_temperature_proto_rawDescOnce sync.Once
	file_temperature_proto_rawDescData []byte
)

func file_temperature_proto_rawDescGZIP() []byte {
	file_temperature_proto_rawDescOnce.Do(func() {
		file_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)))
	})
	return file_temperature_proto_rawDescData
}

var file_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temperature_proto_goTypes = []any{
	(*CelsiusRequest)(nil),      // 0: temperature.CelsiusRequest
	(*FahrenheitRequest)(nil),   // 1: temperature.FahrenheitRequest
	(*TemperatureResponse)(nil), // 2: temperature.TemperatureResponse
}
var file_temperature_proto_depIdxs = []int32{
	0, // 0: temperature.TemperatureConverter.ConvertCelsiusToFahrenheit:input_type -> temperature.CelsiusRequest
	1, // 1: temperature.TemperatureConverter.ConvertFahrenheitToCelsius:input_type -> temperature.FahrenheitRequest
	2, // 2: temperature.TemperatureConverter.ConvertCelsiusToFahrenheit:output_type -> temperature.TemperatureResponse
	2, // 3: temperature.TemperatureConverter.ConvertFahrenheitToCelsius:output_type -> temperature.TemperatureResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temperature_proto_init() }
func file_temperature_proto_init() {
	if File_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temperature_proto_goTypes,
		DependencyIndexes: file_temperature_proto_depIdxs,
		MessageInfos:      file_temperature_proto_msgTypes,
	}.Build()
	File_temperature_proto = out.File
	file_temperature_proto_goTypes = nil
	file_temperature_proto_depIdxs = nil
}
