// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "post": {
                "description": "Converts a temperature from Celsius to Fahrenheit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "Convert Celsius to Fahrenheit",
                "parameters": [
                    {
                        "description": "Temperature in Celsius",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful conversion",
                        "schema": {
                            "$ref": "#/definitions/main.ConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-fahrenheit": {
            "post": {
                "description": "Converts a temperature from Fahrenheit to Celsius",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "Convert Fahrenheit to Celsius",
                "parameters": [
                    {
                        "description": "Temperature in Fahrenheit",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.FahrenheitConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful conversion",
                        "schema": {
                            "$ref": "#/definitions/main.ConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ConversionRequest": {
            "description": "Request body for temperature conversion",
            "type": "object",
            "properties": {
                "celsius": {
                    "description": "Temperature in Celsius",
                    "type": "number",
                    "example": 25
                }
            }
        },
        "main.ConversionResponse": {
            "description": "Response containing both Celsius and Fahrenheit temperatures",
            "type": "object",
            "properties": {
                "celsius": {
                    "description": "Temperature in Celsius",
                    "type": "number",
                    "example": 25
                },
                "fahrenheit": {
                    "description": "Temperature in Fahrenheit",
                    "type": "number",
                    "example": 77
                }
            }
        },
        "main.FahrenheitConversionRequest": {
            "description": "Request body for Fahrenheit to Celsius conversion",
            "type": "object",
            "properties": {
                "fahrenheit": {
                    "description": "Temperature in Fahrenheit",
                    "type": "number",
                    "example": 77
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Temperature Converter API",
	Description:      "Response containing both Celsius and Fahrenheit temperatures",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
